### ISSUE TITLE
ADD: Deep-link QR code

### ISSUE THREAD

**Issue by jpthor** [voltix-vault/voltix-ios#248]
During testing, some users do not open Voltix first, they go straight to QR code, which goes to website

use deep-linking to be smart
https://developer.apple.com/ios/universal-links/

<img width="458" alt="image" src="https://github.com/voltix-vault/voltix/assets/41815753/ece0a58c-450c-4f96-b44b-b7d118bbb6f9">
<img width="457" alt="image" src="https://github.com/voltix-vault/voltix/assets/41815753/7291c330-39c8-47da-b361-c61ceac4de9f">

**Comment by Rockindash** [comment]
Add the path to switch to the Vault when tapped on Switch Vault.
In case of the wrong vault is selected for the Keysign flow.
