### ISSUE TITLE
Send: Error after scanning QR to input receipient address

### ISSUE THREAD

**Issue by SamYap0** [voltix-vault/voltix-ios#273]
In asset send function, when I use camera QR scanning function to input receipient address, then click “Continue”; receive error as attached.

![IMG_1272](https://github.com/voltix-vault/voltix/assets/96066776/7ae501c0-9e84-45a7-91fb-1a87ace2d53c)

I need to manually press/click into the “To” field, then only I can click “Continue” without error after that

**Comment by johnnyluo** [comment]
Just tried on my phone , it seems working as expected , @enriquesouza please double check this one , if it has been fixed , feel free to close it

**Comment by SamYap0** [comment]
Still not working for me.

I have a video, but it’s too large to attach here.
