### ISSUE TITLE
Send: Error when sending SOL

### ISSUE THREAD

**Issue by SamYap0** [voltix-vault/voltix-ios#274]
Error when sending SOL to another address. Note: I tried sending Max.

After pairing my two devices, and both started the keysign process; after a while, the initiator device just keeps spinning:

![IMG_6124](https://github.com/voltix-vault/voltix/assets/96066776/c2af551c-9b9f-4824-84e0-cd2057353b82)

While the second device shows this:

![696ba520-a247-4f21-a509-8ab4dbc7e9ec](https://github.com/voltix-vault/voltix/assets/96066776/615a140f-cf82-4a60-a27d-46d40d9fde3b)

**Comment by enriquesouza** [comment]
Did you try again?

**Comment by SamYap0** [comment]
I tried a few times last night; I’ll try again tonight when I have wifi. 👍

**Comment by SamYap0** [comment]
Finally had wifi to try. Tried first with less than Max.
1st time: time out
2nd time: it shows success, but no Tx recorded (I forgot to copy the hash shown)
3rd: success!

Then I tried another Tx, this time with Max.
The second (non originator phone) had error screen: 
![IMG_6138](https://github.com/voltix-vault/voltix/assets/96066776/3ccd6ebf-9a20-455f-8868-f5e565747545)

**Comment by SamYap0** [comment]
Add on: if I reduce the send amount slightly lower than Max; it seems to give a successful Tx, but the hash doesn’t exist on the blockchain:

hash: 28GAZb19WkG2YF9bqxv485MrNi1oMdxZiJc2zCJXSuKKGsF6LkUQPokmrAJZxdDjcodzZdAtJXWW7TccNvjBhRph

![Uploading IMG_6139.png…]()

**Comment by enriquesouza** [comment]
I am having a look at this.
