### ISSUE TITLE
Error: Sending max RUNE

### ISSUE THREAD

**Issue by SamYap0** [voltix-vault/voltix-ios#284]
I had 1.2 RUNE, tried to send max (1.18 RUNE + 0.02 RUNE gas), the Tx was executed, but error: 

https://runescan.io/tx/C303FD8B3ADDA9FBDF4495162140E090E54BF67C786F3C2D23DBDC1B83ADE4CE

**Comment by enriquesouza** [comment]
Fixed https://github.com/voltix-vault/voltix-ios/pull/327
