### ISSUE TITLE
Vault Creation - Various UI/UX

### ISSUE THREAD

**Issue by Runetard** [voltix-vault/voltix-ios#302]
Whilst attempting to create a new Vault with MacBook Pro and iPhone 13 Pro, various issues arose:

- [ ] Changing WiFi after the app opened was ineffective. Needed to close both applications and reopen for it to work.
- [ ] Devices not found on WiFi (2.4 or 5), needed the camera to join
- [ ] It was not optimally clear how to start the vault generation process (do both devices need to be open, Create, and then one press 'join'?). UX improvements here for sure.
- [ ] Vault Create failed twice (2 min timeout) but there was no indication of progress or if it was still attempting. Perhaps a progress bar or 2min countdown?
- [ ] After the vault failed, there was no 'retry' button or failure summary, had to arrow back and start again manually. 

Happy to elaborate on any or all points.

**Comment by jpthor** [comment]
2nd point - " Devices not found on WiFi (2.4 or 5), needed the camera to join"
What do you mean exactly?

Camera is imperative to join the pairing process. First use camera, then join. 


3rd Point - "Not clear how to start the process"
Will address

4th Point - auto-retries coming soon

**Comment by jpthor** [comment]
<img width="487" alt="image" src="https://github.com/voltix-vault/voltix-ios/assets/41815753/3fb35f74-0524-47c7-a743-aad178affb56">
