### ISSUE TITLE
[Swaps] Swaps fee multiplier

### ISSUE THREAD

**Issue by flypaper0** [voltix-vault/voltix-ios#307]
Implement outbound fees multiplier - x1.5

**Comment by johnnyluo** [comment]
Just apply 1.5x gas for UTXO chains(BTC/BCH/DOGE/LTC) ,  EVM(ETH,AVAX)  for sending swap inbound transaction to make sure the transaction can be commit to block faster

THORChain is fixed , cosmos doesn't need to , BSC is always very cheap , doesn't need to either
