### ISSUE TITLE
"Failed to Simulate Swap"

### ISSUE THREAD

**Issue by mikepocket** [voltix-vault/voltix-ios#314]
**Describe the bug**
When trying to perform a swap it directly shows the Error "Failed to Simulate Swap" as I try to enter 0.01 as the amount to swap.

**To Reproduce**
1. Go to "swap"
2. Click on "Enter Amount"
3. Enter "0."

**Expected behavior**
There shouldn't be an error until I press "Continue" which then should tell me that it is too less or something like that.

**Screenshots**
<img width="302" alt="image" src="https://github.com/voltix-vault/voltix/assets/23121083/ac71824b-6821-436d-be10-596299d889a8">

**Comment by johnnyluo** [comment]
The error here is not user friendly.
[]  Do not request quote if the amount is 0 , firstly it is no point of doing that , secondly , it will be rate limited by the api endpoint quickly
[]  Do not user alert to show the error message, instead show an error message in red color, below `estimate fee` , disable "continue" button
[] When "quote.expectedAmountOut" is empty , show error as swap amount too small
