### ISSUE TITLE
Edit “number of devices needed”

### ISSUE THREAD

**Issue by SamYap0** [voltix-vault/voltix-ios#333]
**Describe the bug**
On the “Create Vault” or “Reshare” page, it’s stated “You need 3 devices”. 

**To Reproduce**
On the “Create Vault” or “Reshare” page

**Expected behavior**
Let’s change it to “You need 2, 3 or 4 devices”

**Screenshots**
![IMG_6250](https://github.com/voltix-vault/voltix-ios/assets/96066776/2ad99006-a91e-4863-bf66-5d792e97779f)

**Smartphone (please complete the following information):**
 - Device: iPhone 14
 - OS: iOS17.4.1
 - Version: 1.0

**Comment by Mansarde** [comment]
Is the maximum 4 devices?
Otherwise we could say "You need at least 2 devices".

**Comment by johnnyluo** [comment]
> Is the maximum 4 devices? Otherwise we could say "You need at least 2 devices".

You can have more than 4

**Comment by johnnyluo** [comment]
Close this one , directly changed on main https://github.com/voltix-vault/voltix-ios/commit/b6d87327718fbc204b9bd7b94ed9aded6e38b663
