### ISSUE TITLE
[BUG] Swap Insufficient funds bug

### ISSUE THREAD

**Issue by johnnyluo** [voltix-vault/voltix-ios#339]
**Describe the bug**
Trying to swap from USDC to LTC , even I have $200 USDC , and also enough ETH to pay for the gas , but it still says "Insufficient funds"

**To Reproduce**
1. Choose an ERC20 token , make sure you have enough balance 
2. Click swap button to swap screen 
3. Choose a to asset  
4. type in the amount, for example , $150 
5. See the screen show "Insufficient funds" and doesn't allow swap

**Expected behavior**
1. Swap should be allowed 

**Screenshots**
<img width="953" alt="image" src="https://github.com/voltix-vault/voltix-ios/assets/749608/7dedcdf9-d7e0-4ef2-b029-1501eddc7ad3">

<img width="899" alt="image" src="https://github.com/voltix-vault/voltix-ios/assets/749608/157af4ee-6094-43bd-8601-b810b44a855d">

**Additional context**

**Comment by flypaper0** [comment]
Swap tx
https://runescan.io/tx/5c659e797b2ef7c36b4a538f418f088f21a5f21bc919cb4e697aff2e6928d6ac
