### ISSUE TITLE
Export/Import Vault Shares as Seed Phrase

### ISSUE THREAD

**Issue by SamYap0** [voltix-vault/voltix-ios#353]
**Is your feature request related to a problem? Please describe.**
Currently, Vault Shares are exported/imported as a human-unreadable DAT file, so practically likely stored on hot devices, and no way to “backup cold” e.g. writing on paper.

**Describe the solution you'd like**
Export/Import Vault Shares as Seed Phrase

**Comment by jpthor** [comment]
Not possible. Vault shares are a very specific implementation.
