### ISSUE TITLE
Creating New Vault: Not User Friendly

### ISSUE THREAD

**Issue by teodor-james** [voltix-vault/voltix-ios#383]
Steps to creating a New Vault are not simple to the user that does not click and play around. 

Confusion comes because you need 2 devices to log on and there are two buttons START and JOIN. Each of which needs to be clicked by each different device.

For an easier user experience, the user needs to know that on their desktop they need to click START while on their phone they need to click JOIN, or vice versa.

DEVICE 1 - START
DEVICE 2 - JOIN

It is not clear that those are the steps that must occur to create a new vault, as the majority of apps and websites have LOGIN and SIGN UP, which is the impression those two buttons give. 

When clicking START, and selecting WIFI - user initial thought is that the 2nd device will just appear since it is also connected to either WIFI, Hotspot or Cellular signal.
![WhatsApp Image 2024-05-03 at 09 49 45](https://github.com/voltix-vault/voltix-ios/assets/168839075/e9b2f172-9cfe-4856-a9d3-22d49d52eceb)

**Comment by jpthor** [comment]
Addressed in #356
