### ISSUE TITLE
[BUG] Send transactions fails every time max amount is used

### ISSUE THREAD

**Issue by Rockindash** [voltix-vault/voltix-ios#385]
**Describe the bug**
When using the max button on the amount text field for send transaction. The flow always fails, my guess is that it is not accounting for gas when fetching the wallet balance.

**To Reproduce**
1. Choose a chain and tap on send.
2. Use the max button for the amount field and press continue.
3. Verify the details and tap next.
4. You will get the error message screen with "failToStart" text.

**Expected behavior**
Should send the maximum amount of crypto based on account balance.

**Screenshots**

After the max button is tapped
![Simulator Screenshot - iPhone 15 Pro - 2024-05-03 at 16 28 37](https://github.com/voltix-vault/voltix-ios/assets/13535088/f6d8638a-c570-443f-ba14-5275c2a5386c)

Error message
![Simulator Screenshot - iPhone 15 Pro - 2024-05-03 at 16 28 55](https://github.com/voltix-vault/voltix-ios/assets/13535088/c7a7dd1d-f3c7-4a1b-bcbf-7382d860dc1a)

**Comment by enriquesouza** [comment]
https://github.com/voltix-vault/voltix-ios/pull/390
